const router = require('express').Router()
const auth = require('../middlewares/auth')

const { catchErrors } = require('./../handlers/errorHandler')
const userContoller = require('../controllers/userController')
router.post("/login", catchErrors(userContoller.login))
router.get("/logout", catchErrors(userContoller.logout))
router.post("/register", catchErrors(userContoller.register))
router.get("/getuserdetails", catchErrors(userContoller.getuserdetails))
router.put("/editpassword/:userid", catchErrors(userContoller.editpassword))
router.delete("/deleteuser/:userid", catchErrors(userContoller.deleteuser))
router.post("/createcompany", catchErrors(userContoller.createcompany))
router.get("/getcompdetails", catchErrors(userContoller.getcompdetails))
router.post("/addcategory", catchErrors(userContoller.addcategory))
router.get("/getCategories", catchErrors(userContoller.getcategories))
router.get("/getcategory", catchErrors(userContoller.getcategory))
router.post("/creditupdate", catchErrors(userContoller.creditupdate))
router.put("/checkpassword", catchErrors(userContoller.checkpassword))
router.put("/selectupdate/:candidate_id", catchErrors(userContoller.selectupdate))
router.put("/getcv", catchErrors(userContoller.getcv))
router.post("/downloadfile/:filename", catchErrors(userContoller.downloadfile))
router.put("/questionupload", catchErrors(userContoller.questionupload))
router.put("/editcredit/:userid", catchErrors(userContoller.editcredit))
// router.post("/validation", auth, catchErrors(userContoller.login))

module.exports = router
